# .github/ISSUE_TEMPLATE/bug_report.yml
name: 🐛 Bug Report
description: Report a reproducible bug in the project
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the following so we can reproduce and fix it quickly.
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Short description of the issue
      placeholder: e.g., Crash when adding new transaction
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do we reproduce this bug?
      placeholder: 1. Go to ...  2. Click ...  3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
  - type: input
    id: version
    attributes:
      label: App Version / Branch
      placeholder: e.g., v0.1.0 or feature/debt-optimizer
