# .github/ISSUE_TEMPLATE/security_vulnerability.yml
name: 🔒 Security Vulnerability
description: Report a potential security issue (will be handled privately)
labels: [security]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Please do not share sensitive details publicly. 
        For critical issues, email **kareemaiman2012@gmail.com** instead.
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      placeholder: e.g., Found SQL injection risk in login
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      placeholder: What could an attacker achieve?
